### ISSUE TITLE
버그 및 건의사항

### ISSUE THREAD

**Issue by nasras520** [Any-Material/Aishite#1]
![1](https://user-images.githubusercontent.com/95084343/143675457-58602700-05d0-47f9-9339-aee82c35af26.png)

처음한번 프로그램 이용후 다시키게되면 FALLBACK문구와 함께 아무것도 할수없습니다 
풀더에서 config파일을 지우면 되긴합니다

![2](https://user-images.githubusercontent.com/95084343/143675475-6a5e59ea-1800-4603-9864-3933411500a0.png)
브라우저를 다끄고나면 다시 킬수있는 방법을 모르겠습니다 
![4](https://user-images.githubusercontent.com/95084343/143675484-841e4822-2930-4deb-899f-b2c77bf93189.png)
이것처럼 생성버튼을 만들어 주실수 있나요?

![3](https://user-images.githubusercontent.com/95084343/143675502-4d038a2a-d3f0-4de5-b350-35041bf8510f.png)
이전버전에서 태그 클릭시 자동으로 입력이 됐었는데 지금은 안되네요 이것도 넣어주실수 있으신가요?

![5](https://user-images.githubusercontent.com/95084343/143675515-728ad812-5760-4222-b7e5-8e82452f2365.png)
페이지도 ...을 눌러서 원하는곳으로 이동할수있게 해주시면 감사하겠습니다

**Comment by Sombian** [comment]
건의 감사합니다!

요청해주신 기능들 전부 추가하도록 하겠습니다만 프로그램을 종료후 재시작시 `FALLBACK` 이 나온다고 하셨는데
혹시 `config.json` 의 내용을 첨부해 주실 수 있으신가요?

**Comment by nasras520** [comment]
2.0.0 압축해제후 바로 프로그램 실행 - 프로그램종료 - 다시 프로그램 실행후 FALLBACK 확인후 config 내용입니다

{"version":"1.0.0","general":{"dependency":["storage"]},"download":{"file":"(id).(extension)","folder":"./downloads/","threads":5,"concurrent":5},"navigator":{"index":0,"pages":[{"type":"C","name":"language:all","args":{"index":0,"query":"language:all"}},{"type":"C","name":"language:korean","args":{"index":0,"query":"language:korean"}}]}}

2.0.0 압축해제후 바로 프로그램 실행 - 기본으로뜨는 language:all 창 종료후 language:korean 창에서 
language:korean artist:bifidus 입력후 프로그램종료 다시 프로그램실행후 FALLBACK 확인후 config 내용입니다

{"version":"1.0.0","general":{"dependency":["storage"]},"download":{"file":"(id).(extension)","folder":"./downloads/","threads":5,"concurrent":5},"navigator":{"index":0,"pages":[{"type":"C","name":"language:korean artist:bifidus","args":{"index":0,"query":"language:korean artist:bifidus"}}]}}

**Comment by Sombian** [comment]
소중한 정보 감사드립니다. 해당 증상은 빠른 시일내에 조속히 해결하고자 노력하겠습니다. 아울러 평일에는 작업을 오래하기 힘든 까닭과 더불어, 요청해주신 기능 외에도 기타 추가사항을 작업해야 하는 연유로 시간이 경과될 수 있는점 양해 부탁바랍니다.

**Comment by nasras520** [comment]
현재 어떤거든 만화를 이용하려해도 이미지로딩이 안되고 빈화면만 뜹니다

**Comment by Sombian** [comment]
> 현재 어떤거든 만화를 이용하려해도 이미지로딩이 안되고 빈화면만 뜹니다

개발버전에선 해결했습니다만 오늘중에 미완성이라도 임시로 신버전 올리도록 하겠습니다. 불편을 끼쳐서 죄송합니다.

**Comment by Sombian** [comment]
[2.0.1](https://github.com/Any-Material/Aishite/releases/tag/2.0.1) 확인 바랍니다.
최근에 꽤나 바쁜 까닭에 기능 한개를 미처 추가하지 못했습니다만 넓은 아량으로 양해해 주시길 바랍니다.
또한 미해결된 증상이 있을경우 현 issue 에 comment 추가 바라며, 신규 증상의 경우 새 issue 를 발행해 주시길 바랍니다. 감사합니다.

**Comment by Sombian** [comment]
https://github.com/Any-Material/Aishite/commit/e7e41002f731a53f0887e05919fcf33b1eb2b726 에서 해결
