### ISSUE TITLE
앞으로 디코없이 사이트에서만 소통하시나요?

### ISSUE THREAD

**Issue by nasras520** [Any-Material/Aishite#3]
디코가 없어졌길래 문의드립니다
이제 홈페이지에서만 소통하시는지 
아니면 더이상 업데이트를 안하실 예정이신지 궁금합니다

**Comment by Sombian** [comment]
저 혼자만 몇년째 떠드는게 너무 정신적으로 힘들어서 디코 서버 폭파시켰습니다.
앞으로는 Github 에서만 소통할 예정이오니 많은 관심 바랍니다.
