### ISSUE TITLE
건의사항

### ISSUE THREAD

**Issue by nasras520** [Any-Material/Aishite#4]
![1](https://user-images.githubusercontent.com/95084343/166137514-0f35895e-c874-4d65-b15b-0b79311809b5.png)
![2](https://user-images.githubusercontent.com/95084343/166137516-fbe00d27-1d04-49fe-b638-4d51a0f05a20.png)

별거 아니긴한데
위가 최근버전
아래가 그이전버전입니다 
글꼴이 변경된것같은데 조금 올드해보입니다
이전버전으로 바꿔주시거나 아니면 개인적으로 바꿀수있는 방법을 알려주실수 있으신가요?

그리고 language:korean popular:week 와 popular:week 로했을시 검색결과값이 다릅니다
한국어가아닌 작품을 제외하고 같은 한국어태그가 달려있음에도 노출되는 작품이 아예 다릅니다 

그리고 검색창에 우클릭을 가능하게 해주실수 있으신가요?
복붙할때 조금 불편합니다

프로그램을 껏다켰을때 검색한것은 저장되있는것처럼
줌인 줌아웃상태도 한번설정한채로 어느작품을 보던 똑같이 설정돼있으면 합니다

항상감사합니다

**Comment by Sombian** [comment]
1. 글꼴은 바꿔 보도록 하겠습니다.
2. 검색 결과는 왼쪽에서 우측으로 연산합니다. 예시로, `language:korean popular:week` 와 `popular:week language:korean` 두 경우 내용물은 같지만 순서가 다를 수 있습니다.
3. 우클릭의 용도가 무엇인지 모르겠습니다. context menu 말씀이신지요?
4. 모든 viewer (page) 의 확대 정도를 전부 제어하는 것 보단 기본 값을 추가하는게 더 좋아보입니다.

**Comment by nasras520** [comment]
![123](https://user-images.githubusercontent.com/95084343/166220660-1c35280d-1837-4492-b958-4f60ae511eaa.png)
3번같은경우는 말씀하신게 맞습니다
원하는태그나 작가같은걸 바로바로 우클릭 복붙메뉴로 하고싶은데 키보드로 컨트롤c 컨트롤v하는게 조금 불편해서 그렇습니다
추가해주시면 감사하겠습니다

4번같은경우 새버전으로 넘어오면서 기본으로 확대돼있는 정도가 조금 작아져있는데 이게 기본으로 돼있어서 얘도 마찬가지로 마우스로 조정이 불가능하고 매 작품마다 컨트롤을 누르고 조정을 해줘야해서 불편합니다 기본값을 설정하게 바꿔주시면 감사하겠습니다

늘 감사합니다 항상 프로그램 잘 이용하고있습니다

**Comment by Sombian** [comment]
https://github.com/Any-Material/Aishite/releases/tag/2.1.2 확인 바랍니다.
